-- Observed application schema, metadata-only snapshot 2026-09-20.

-- EMPTY Supabase project only. Follow with targeted_permissions in the same reset.

-- Managed auth/storage schemas and Supabase roles must already exist.

-- No production data, no sequence current values, no auth secrets.

begin;

set local search_path = public;

set local check_function_bodies = false;

DO $$ BEGIN IF to_regclass('public.listing') IS NOT NULL THEN RAISE EXCEPTION 'Baseline requires an empty application schema; never apply to production'; END IF; END $$;

CREATE EXTENSION IF NOT EXISTS unaccent WITH SCHEMA public;

CREATE TYPE public."additional_services_enum" AS ENUM ('Visite de la ferme', 'Ateliers de cuisine', 'Hébergement', 'Activités pour enfants', 'Réservation pour événements');

CREATE TYPE public."availability_enum" AS ENUM ('Saisonnière', 'Toute lannée', 'Pré-commande', 'Sur abonnement', 'Événements spéciaux');

CREATE TYPE public."certification_enum" AS ENUM ('Label AB', 'Label Rouge', 'AOP/AOC', 'HVE', 'Demeter');

CREATE TYPE public."product_type_enum" AS ENUM ('Fruits', 'Légumes', 'Produits laitiers', 'Viande', 'Œufs', 'Produits transformés');

CREATE TYPE public."production_method_enum" AS ENUM ('Agriculture conventionnelle', 'Agriculture biologique', 'Agriculture durable', 'Agriculture raisonnée');

CREATE TYPE public."purchase_mode_enum" AS ENUM ('Vente directe à la ferme', 'Marché local', 'Livraison à domicile', 'Point de vente collectif', 'Drive fermier');

CREATE SEQUENCE public."farmer_requests_id_seq" AS integer START WITH 1 INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 NO CYCLE;

CREATE SEQUENCE public."orders_id_seq" AS bigint START WITH 1 INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 NO CYCLE;

CREATE SEQUENCE public."review_reports_id_seq" AS bigint START WITH 1 INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 NO CYCLE;

CREATE SEQUENCE public."review_votes_id_seq" AS bigint START WITH 1 INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 NO CYCLE;

CREATE SEQUENCE public."reviews_id_seq" AS bigint START WITH 1 INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 NO CYCLE;

CREATE TABLE public."farmer_requests" (
  "id" integer DEFAULT nextval('farmer_requests_id_seq'::regclass) NOT NULL,
  "created_at" timestamp with time zone DEFAULT now(),
  "user_id" text NOT NULL,
  "email" character varying NOT NULL,
  "farm_name" character varying NOT NULL,
  "location" character varying NOT NULL,
  "description" text,
  "products" text,
  "website" text,
  "status" character varying DEFAULT 'pending'::character varying,
  "first_name" text,
  "last_name" text,
  "siret" text,
  "approved_by_admin_at" timestamp with time zone,
  "validated_by" text,
  "admin_reason" text,
  "updated_at" timestamp with time zone DEFAULT now(),
  "lat" double precision,
  "lng" double precision,
  "phoneNumber" text
);

CREATE TABLE public."listing" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY (SEQUENCE NAME public."listing_id_seq" START WITH 1 INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 NO CYCLE) NOT NULL,
  "created_at" timestamp with time zone DEFAULT now() NOT NULL,
  "coordinates" json,
  "active" boolean DEFAULT false,
  "typeferme" character varying,
  "phoneNumber" character varying,
  "email" character varying,
  "website" character varying,
  "certifications" certification_enum[],
  "description" text,
  "name" character varying,
  "profileImage" character varying,
  "fullName" character varying,
  "product_type" product_type_enum[],
  "purchase_mode" purchase_mode_enum[],
  "production_method" production_method_enum[],
  "availability" availability_enum[],
  "additional_services" additional_services_enum[],
  "address" text,
  "updated_at" timestamp with time zone DEFAULT now(),
  "lat" double precision,
  "lng" double precision,
  "published_at" timestamp with time zone,
  "modified_at" timestamp with time zone,
  "opening_hours" jsonb,
  "pickup_days" text,
  "delivery_available" boolean DEFAULT false NOT NULL,
  "founded_year" date,
  "orders_enabled" boolean DEFAULT false NOT NULL,
  "clerk_user_id" text,
  "osm_id" bigint,
  "slug" text NOT NULL
);

CREATE TABLE public."listingImages" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY (SEQUENCE NAME public."listingImages_id_seq" START WITH 1 INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 NO CYCLE) NOT NULL,
  "created_at" timestamp with time zone DEFAULT now() NOT NULL,
  "url" character varying,
  "listing_id" bigint
);

CREATE TABLE public."listing_claim_requests" (
  "id" uuid DEFAULT gen_random_uuid() NOT NULL,
  "created_at" timestamp with time zone DEFAULT now() NOT NULL,
  "updated_at" timestamp with time zone DEFAULT now() NOT NULL,
  "listing_id" integer NOT NULL,
  "clerk_user_id" text NOT NULL,
  "contact_email" text NOT NULL,
  "contact_phone" text,
  "message" text,
  "status" text DEFAULT 'pending'::text NOT NULL,
  "reviewed_at" timestamp with time zone,
  "reviewed_by" text,
  "contact_name" text,
  "verification_method" text,
  "verification_code" text,
  "code_expires_at" timestamp with time zone,
  "code_attempts" integer DEFAULT 0,
  "verified_at" timestamp with time zone,
  "siret" text,
  "siret_verified" boolean DEFAULT false,
  "siret_company_name" text
);

CREATE TABLE public."orders" (
  "id" bigint DEFAULT nextval('orders_id_seq'::regclass) NOT NULL,
  "user_id" text NOT NULL,
  "farm_id" bigint NOT NULL,
  "delivery_mode" text NOT NULL,
  "delivery_day" text,
  "total_price" numeric(10,2) DEFAULT 0 NOT NULL,
  "status" text DEFAULT 'pending'::text NOT NULL,
  "items" jsonb DEFAULT '[]'::jsonb NOT NULL,
  "created_at" timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
  "updated_at" timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
  "payment_status" text DEFAULT 'unpaid'::text,
  "delivery_address" jsonb,
  "customer_notes" text,
  "farmer_notes" text,
  "cancelled_reason" text,
  "cancelled_by" text,
  "metadata" jsonb DEFAULT '{}'::jsonb
);

CREATE TABLE public."osm_import_review" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY (SEQUENCE NAME public."osm_import_review_id_seq" START WITH 1 INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 NO CYCLE) NOT NULL,
  "osm_id" bigint,
  "name" text,
  "lat" double precision,
  "lng" double precision,
  "address" text,
  "website" text,
  "phoneNumber" text,
  "email" text,
  "fullName" text,
  "typeferme" text,
  "active" boolean DEFAULT false,
  "description" text,
  "opening_hours" jsonb,
  "founded_year" text,
  "confidence" text,
  "match_reason" text,
  "quality_score" integer,
  "tags" jsonb,
  "raw" jsonb,
  "status" text DEFAULT 'pending'::text,
  "note" text,
  "created_at" timestamp with time zone DEFAULT now()
);

CREATE TABLE public."producer_requests" (
  "id" uuid DEFAULT gen_random_uuid() NOT NULL,
  "type" text NOT NULL,
  "user_id" text NOT NULL,
  "user_email" text NOT NULL,
  "user_name" text,
  "farm_name" text,
  "first_name" text,
  "last_name" text,
  "phone" text,
  "siret" text,
  "location" text,
  "lat" double precision,
  "lng" double precision,
  "description" text,
  "products" text,
  "website" text,
  "listing_id" bigint,
  "status" text DEFAULT 'pending'::text NOT NULL,
  "admin_note" text,
  "reviewed_by" text,
  "reviewed_at" timestamp with time zone,
  "created_at" timestamp with time zone DEFAULT now() NOT NULL,
  "updated_at" timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE public."products" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY (SEQUENCE NAME public."products_id_seq" START WITH 1 INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 NO CYCLE) NOT NULL,
  "listing_id" bigint,
  "name" text NOT NULL,
  "description" text,
  "price" numeric(10,2),
  "unit" text,
  "available" boolean DEFAULT true,
  "created_at" timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
  "labels" text[],
  "stock_quantity" integer DEFAULT 0,
  "min_stock" integer DEFAULT 5 NOT NULL,
  "sku" character varying(50),
  "category" character varying(100),
  "image_url" text,
  "seasonal" boolean DEFAULT false NOT NULL,
  "season_start" date,
  "season_end" date,
  "updated_at" timestamp with time zone DEFAULT now(),
  "is_published" boolean DEFAULT true NOT NULL,
  "farm_id" bigint,
  "active" boolean DEFAULT true NOT NULL,
  "stock_status" text DEFAULT 'in_stock'::text NOT NULL
);

CREATE TABLE public."profiles" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY (SEQUENCE NAME public."profiles_id_seq" START WITH 1 INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 NO CYCLE) NOT NULL,
  "created_at" timestamp with time zone DEFAULT now() NOT NULL,
  "user_id" text,
  "email" text,
  "role" text DEFAULT 'user'::text,
  "farm_id" bigint,
  "favorites" jsonb DEFAULT '[]'::jsonb,
  "updated_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE public."review_reports" (
  "id" bigint DEFAULT nextval('review_reports_id_seq'::regclass) NOT NULL,
  "review_id" bigint NOT NULL,
  "reporter_user_id" text NOT NULL,
  "reason" character varying(50) NOT NULL,
  "description" text,
  "status" character varying(20) DEFAULT 'pending'::character varying,
  "created_at" timestamp with time zone DEFAULT now()
);

CREATE TABLE public."review_votes" (
  "id" bigint DEFAULT nextval('review_votes_id_seq'::regclass) NOT NULL,
  "review_id" bigint NOT NULL,
  "user_id" text NOT NULL,
  "vote_type" character varying(10) NOT NULL,
  "created_at" timestamp with time zone DEFAULT now()
);

CREATE TABLE public."reviews" (
  "id" bigint DEFAULT nextval('reviews_id_seq'::regclass) NOT NULL,
  "listing_id" bigint NOT NULL,
  "user_id" text,
  "rating" integer NOT NULL,
  "title" character varying(200),
  "comment" text NOT NULL,
  "reviewer_name" character varying(100),
  "reviewer_email" character varying(255),
  "is_verified" boolean DEFAULT false,
  "visit_type" character varying(20),
  "purchased_products" jsonb,
  "visit_date" date,
  "helpful_count" integer DEFAULT 0,
  "not_helpful_count" integer DEFAULT 0,
  "reported_count" integer DEFAULT 0,
  "status" character varying(20) DEFAULT 'pending'::character varying,
  "moderated_by" text,
  "moderated_at" timestamp with time zone,
  "rejection_reason" text,
  "created_at" timestamp with time zone DEFAULT now(),
  "updated_at" timestamp with time zone DEFAULT now(),
  "ip_address" inet,
  "user_agent" text,
  "source" character varying(50) DEFAULT 'website'::character varying
);

ALTER SEQUENCE public."orders_id_seq" OWNED BY public."orders"."id";

ALTER SEQUENCE public."review_reports_id_seq" OWNED BY public."review_reports"."id";

ALTER SEQUENCE public."review_votes_id_seq" OWNED BY public."review_votes"."id";

ALTER SEQUENCE public."reviews_id_seq" OWNED BY public."reviews"."id";

ALTER SEQUENCE public."farmer_requests_id_seq" OWNED BY public."farmer_requests"."id";

CREATE OR REPLACE FUNCTION public.current_clerk_user_id()
 RETURNS text
 LANGUAGE sql
 STABLE
AS $function$
  select auth.jwt() ->> 'sub';
$function$;

CREATE OR REPLACE FUNCTION public.generate_claim_code()
 RETURNS text
 LANGUAGE sql
AS $function$
  SELECT LPAD(FLOOR(RANDOM() * 1000000)::TEXT, 6, '0');
$function$;

CREATE OR REPLACE FUNCTION public.handle_farmer_request_approval()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
DECLARE
  new_listing_id BIGINT;
BEGIN
  -- Vérifier que le status est passé à "approved" (et n'était pas déjà approved)
  IF NEW.status = 'approved' AND (OLD.status IS NULL OR OLD.status != 'approved') THEN

    -- ✅ Bypass interne pour autoriser les updates sensibles sur profiles depuis ce trigger
    perform set_config('app.bypass_sensitive', 'on', true);

    -- 1) Créer / mettre à jour le profile avec role='farmer'
    INSERT INTO public.profiles (
      user_id,
      email,
      role,
      farm_id,
      created_at,
      updated_at
    ) VALUES (
      NEW.user_id,
      NEW.email,
      'farmer',
      NULL,
      NOW(),
      NOW()
    )
    ON CONFLICT (user_id) DO UPDATE SET
      role = 'farmer',
      email = EXCLUDED.email,
      updated_at = NOW();

    -- 2) Créer le listing (active=false, orders_enabled=false)
    INSERT INTO public.listing (
      clerk_user_id,
      name,
      description,
      email,
      "phoneNumber",
      website,
      address,
      lat,
      lng,
      active,
      orders_enabled,
      delivery_available,
      created_at,
      updated_at
    ) VALUES (
      NEW.user_id,
      NEW.farm_name,
      NEW.description,
      NEW.email,
      NEW."phoneNumber",
      NEW.website,
      NEW.location,
      NEW.lat,
      NEW.lng,
      false,
      false,
      false,
      NOW(),
      NOW()
    )
    RETURNING id INTO new_listing_id;

    -- 3) Mettre à jour le profile avec le farm_id
    UPDATE public.profiles
    SET
      farm_id = new_listing_id,
      updated_at = NOW()
    WHERE user_id = NEW.user_id;

    RAISE NOTICE 'Profile et listing créés automatiquement pour user_id=%, listing_id=%',
      NEW.user_id, new_listing_id;
  END IF;

  RETURN NEW;
END;
$function$;

CREATE OR REPLACE FUNCTION public.handle_producer_request_approval()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
DECLARE
  new_listing_id BIGINT;
BEGIN
  IF NEW.status = 'approved' AND OLD.status != 'approved' THEN
    
    -- Crée ou met à jour le profil
    INSERT INTO public.profiles (user_id, email, role)
    VALUES (NEW.user_id, NEW.user_email, 'farmer')
    ON CONFLICT (user_id) DO UPDATE
      SET role = 'farmer';

    -- Crée le listing vide
    INSERT INTO public.listing (
      clerk_user_id,
      name,
      description,
      "phoneNumber",
      website,
      address,
      lat,
      lng,
      active,
      orders_enabled,
      delivery_available,
      slug
    ) VALUES (
      NEW.user_id,
      NEW.farm_name,
      NEW.description,
      NEW.phone,
      NEW.website,
      NEW.location,
      NEW.lat,
      NEW.lng,
      false,
      false,
      false,
      lower(regexp_replace(
        regexp_replace(
          COALESCE(NEW.farm_name, 'ferme') || '-' ||
          EXTRACT(EPOCH FROM NOW())::BIGINT::TEXT,
          '[^a-zA-Z0-9\-]', '-', 'g'
        ),
        '-+', '-', 'g'
      ))
    )
    ON CONFLICT (slug) DO NOTHING
    RETURNING id INTO new_listing_id;

    -- Met à jour listing_id dans producer_requests
    IF new_listing_id IS NOT NULL THEN
      UPDATE public.producer_requests
        SET listing_id = new_listing_id
        WHERE id = NEW.id;
    END IF;

  END IF;
  RETURN NEW;
END;
$function$;

CREATE OR REPLACE FUNCTION public.is_admin()
 RETURNS boolean
 LANGUAGE sql
 STABLE SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
  select
    -- ✅ Bootstrap: email admin (si présent dans le JWT)
    coalesce(lower(auth.jwt() -> 'user_metadata' ->> 'email'), '') = 'admin@farmtofork.fr'
    OR
    coalesce(lower(auth.jwt() ->> 'email'), '') = 'admin@farmtofork.fr'
    OR
    -- ✅ Sinon fallback: role stocké en DB (comme avant)
    exists (
      select 1
      from public.profiles p
      where p.user_id = (auth.jwt() ->> 'sub')
        and p.role = 'admin'
    );
$function$;

CREATE OR REPLACE FUNCTION public.is_farmer()
 RETURNS boolean
 LANGUAGE sql
 STABLE SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
  select exists (
    select 1
    from public.profiles p
    where p.user_id = auth.jwt() ->> 'sub'
      and p.role = 'farmer'
  );
$function$;

CREATE OR REPLACE FUNCTION public.prevent_profile_role_change()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
begin
  -- ✅ bypass interne (activé par handle_farmer_request_approval)
  if coalesce(current_setting('app.bypass_sensitive', true), '') = 'on' then
    return new;
  end if;

  if new.role is distinct from old.role then
    if not public.is_admin() then
      raise exception 'Only admin can change role';
    end if;
  end if;

  return new;
end;
$function$;

CREATE OR REPLACE FUNCTION public.prevent_profiles_sensitive_changes()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
begin
  -- ✅ bypass interne (activé par handle_farmer_request_approval)
  if coalesce(current_setting('app.bypass_sensitive', true), '') = 'on' then
    return new;
  end if;

  if new.role is distinct from old.role then
    if not public.is_admin() then
      raise exception 'Only admin can change role';
    end if;
  end if;

  if (new.user_id is distinct from old.user_id)
     or (new.farm_id is distinct from old.farm_id)
     or (new.email is distinct from old.email) then
    if not public.is_admin() then
      raise exception 'Only admin can change user_id/farm_id/email';
    end if;
  end if;

  return new;
end;
$function$;

CREATE OR REPLACE FUNCTION public.set_updated_at()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$function$;

CREATE OR REPLACE FUNCTION public.update_lcr_updated_at()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$function$;

CREATE OR REPLACE FUNCTION public.update_updated_at_column()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$function$;

ALTER TABLE public."farmer_requests" ADD CONSTRAINT "farmer_requests_coords_required" CHECK (lat IS NULL AND lng IS NULL OR lat IS NOT NULL AND lng IS NOT NULL);

ALTER TABLE public."farmer_requests" ADD CONSTRAINT "farmer_requests_pkey" PRIMARY KEY (id);

ALTER TABLE public."farmer_requests" ADD CONSTRAINT "farmer_requests_status_check" CHECK (status::text = ANY (ARRAY['pending'::character varying::text, 'approved'::character varying::text, 'rejected'::character varying::text]));

ALTER TABLE public."listing" ADD CONSTRAINT "listing_coords_required" CHECK (lat IS NULL AND lng IS NULL OR lat IS NOT NULL AND lng IS NOT NULL);

ALTER TABLE public."listing" ADD CONSTRAINT "listing_osm_id_unique" UNIQUE (osm_id);

ALTER TABLE public."listing" ADD CONSTRAINT "listing_pkey" PRIMARY KEY (id);

ALTER TABLE public."listing" ADD CONSTRAINT "listing_slug_unique" UNIQUE (slug);

ALTER TABLE public."listingImages" ADD CONSTRAINT "listingImages_pkey" PRIMARY KEY (id);

ALTER TABLE public."listing_claim_requests" ADD CONSTRAINT "listing_claim_requests_listing_id_clerk_user_id_key" UNIQUE (listing_id, clerk_user_id);

ALTER TABLE public."listing_claim_requests" ADD CONSTRAINT "listing_claim_requests_pkey" PRIMARY KEY (id);

ALTER TABLE public."listing_claim_requests" ADD CONSTRAINT "listing_claim_requests_status_check" CHECK (status = ANY (ARRAY['pending'::text, 'code_sent'::text, 'verified'::text, 'rejected'::text]));

ALTER TABLE public."listing_claim_requests" ADD CONSTRAINT "listing_claim_requests_verification_method_check" CHECK (verification_method = ANY (ARRAY['email'::text, 'sms'::text]));

ALTER TABLE public."orders" ADD CONSTRAINT "orders_cancelled_by_check" CHECK (cancelled_by = ANY (ARRAY['customer'::text, 'farmer'::text, 'admin'::text]));

ALTER TABLE public."orders" ADD CONSTRAINT "orders_delivery_mode_check" CHECK (delivery_mode = ANY (ARRAY['pickup'::text, 'delivery'::text]));

ALTER TABLE public."orders" ADD CONSTRAINT "orders_payment_status_check" CHECK (payment_status = ANY (ARRAY['unpaid'::text, 'paid'::text, 'refunded'::text]));

ALTER TABLE public."orders" ADD CONSTRAINT "orders_pkey" PRIMARY KEY (id);

ALTER TABLE public."orders" ADD CONSTRAINT "orders_status_check" CHECK (status = ANY (ARRAY['pending'::text, 'confirmed'::text, 'ready'::text, 'delivered'::text, 'cancelled'::text]));

ALTER TABLE public."osm_import_review" ADD CONSTRAINT "osm_import_review_pkey" PRIMARY KEY (id);

ALTER TABLE public."producer_requests" ADD CONSTRAINT "producer_requests_pkey" PRIMARY KEY (id);

ALTER TABLE public."producer_requests" ADD CONSTRAINT "producer_requests_status_check" CHECK (status = ANY (ARRAY['pending'::text, 'approved'::text, 'rejected'::text]));

ALTER TABLE public."producer_requests" ADD CONSTRAINT "producer_requests_type_check" CHECK (type = ANY (ARRAY['create'::text, 'claim'::text]));

ALTER TABLE public."products" ADD CONSTRAINT "products_pkey" PRIMARY KEY (id);

ALTER TABLE public."products" ADD CONSTRAINT "products_stock_status_check" CHECK (stock_status = ANY (ARRAY['in_stock'::text, 'low_stock'::text, 'out_of_stock'::text]));

ALTER TABLE public."profiles" ADD CONSTRAINT "profiles_pkey" PRIMARY KEY (id);

ALTER TABLE public."profiles" ADD CONSTRAINT "profiles_role_check" CHECK (role = ANY (ARRAY['user'::text, 'farmer'::text, 'admin'::text]));

ALTER TABLE public."profiles" ADD CONSTRAINT "profiles_user_id_key" UNIQUE (user_id);

ALTER TABLE public."review_reports" ADD CONSTRAINT "review_reports_pkey" PRIMARY KEY (id);

ALTER TABLE public."review_reports" ADD CONSTRAINT "review_reports_reason_check" CHECK (reason::text = ANY (ARRAY['spam'::character varying::text, 'inappropriate'::character varying::text, 'fake'::character varying::text, 'offensive'::character varying::text, 'other'::character varying::text]));

ALTER TABLE public."review_reports" ADD CONSTRAINT "review_reports_review_id_reporter_user_id_key" UNIQUE (review_id, reporter_user_id);

ALTER TABLE public."review_reports" ADD CONSTRAINT "review_reports_status_check" CHECK (status::text = ANY (ARRAY['pending'::character varying::text, 'resolved'::character varying::text, 'dismissed'::character varying::text]));

ALTER TABLE public."review_votes" ADD CONSTRAINT "review_votes_pkey" PRIMARY KEY (id);

ALTER TABLE public."review_votes" ADD CONSTRAINT "review_votes_review_id_user_id_key" UNIQUE (review_id, user_id);

ALTER TABLE public."review_votes" ADD CONSTRAINT "review_votes_vote_type_check" CHECK (vote_type::text = ANY (ARRAY['helpful'::character varying::text, 'not_helpful'::character varying::text]));

ALTER TABLE public."reviews" ADD CONSTRAINT "reviews_pkey" PRIMARY KEY (id);

ALTER TABLE public."reviews" ADD CONSTRAINT "reviews_rating_check" CHECK (rating >= 1 AND rating <= 5);

ALTER TABLE public."reviews" ADD CONSTRAINT "reviews_status_check" CHECK (status::text = ANY (ARRAY['pending'::character varying::text, 'approved'::character varying::text, 'rejected'::character varying::text, 'hidden'::character varying::text]));

ALTER TABLE public."reviews" ADD CONSTRAINT "reviews_visit_type_check" CHECK (visit_type::text = ANY (ARRAY['delivery'::character varying::text, 'pickup'::character varying::text, 'visit'::character varying::text, 'online'::character varying::text]));

ALTER TABLE public."listingImages" ADD CONSTRAINT "listingImages_listing_id_fkey" FOREIGN KEY (listing_id) REFERENCES listing(id) ON DELETE CASCADE;

ALTER TABLE public."listing_claim_requests" ADD CONSTRAINT "listing_claim_requests_listing_id_fkey" FOREIGN KEY (listing_id) REFERENCES listing(id) ON DELETE CASCADE;

ALTER TABLE public."orders" ADD CONSTRAINT "orders_farm_id_fkey" FOREIGN KEY (farm_id) REFERENCES listing(id) ON DELETE CASCADE;

ALTER TABLE public."producer_requests" ADD CONSTRAINT "producer_requests_listing_id_fkey" FOREIGN KEY (listing_id) REFERENCES listing(id) ON DELETE CASCADE;

ALTER TABLE public."products" ADD CONSTRAINT "products_farm_id_fkey" FOREIGN KEY (farm_id) REFERENCES listing(id) ON DELETE CASCADE;

ALTER TABLE public."products" ADD CONSTRAINT "products_listing_id_fkey" FOREIGN KEY (listing_id) REFERENCES listing(id) ON DELETE CASCADE;

ALTER TABLE public."profiles" ADD CONSTRAINT "profiles_farm_id_fkey" FOREIGN KEY (farm_id) REFERENCES listing(id) ON DELETE SET NULL;

ALTER TABLE public."review_reports" ADD CONSTRAINT "review_reports_review_id_fkey" FOREIGN KEY (review_id) REFERENCES reviews(id) ON DELETE CASCADE;

ALTER TABLE public."review_votes" ADD CONSTRAINT "review_votes_review_id_fkey" FOREIGN KEY (review_id) REFERENCES reviews(id) ON DELETE CASCADE;

ALTER TABLE public."reviews" ADD CONSTRAINT "reviews_listing_id_fkey" FOREIGN KEY (listing_id) REFERENCES listing(id) ON DELETE CASCADE;

CREATE INDEX idx_farmer_requests_email ON public.farmer_requests USING btree (email);

CREATE INDEX idx_farmer_requests_status ON public.farmer_requests USING btree (status);

CREATE INDEX idx_farmer_requests_user_id ON public.farmer_requests USING btree (user_id);

CREATE UNIQUE INDEX uq_farmer_requests_pending_email ON public.farmer_requests USING btree (email) WHERE ((status)::text = 'pending'::text);

CREATE UNIQUE INDEX uq_farmer_requests_pending_user ON public.farmer_requests USING btree (user_id) WHERE ((status)::text = 'pending'::text);

CREATE INDEX idx_listing_active ON public.listing USING btree (active) WHERE (active = true);

CREATE INDEX idx_listing_bounds_created ON public.listing USING btree (lat, lng, created_at DESC) WHERE (active = true);

CREATE INDEX idx_listing_email ON public.listing USING btree (email);

CREATE INDEX idx_listing_lat ON public.listing USING btree (lat);

CREATE INDEX idx_listing_lat_lng ON public.listing USING btree (lat, lng) WHERE (active = true);

CREATE INDEX idx_listing_lng ON public.listing USING btree (lng);

CREATE INDEX listing_clerk_user_id_idx ON public.listing USING btree (clerk_user_id);

CREATE UNIQUE INDEX listing_clerk_user_id_unique ON public.listing USING btree (clerk_user_id) WHERE (clerk_user_id IS NOT NULL);

CREATE INDEX listing_slug_idx ON public.listing USING btree (slug);

CREATE INDEX idx_listingimages_listing_id ON public."listingImages" USING btree (listing_id);

CREATE INDEX idx_lcr_clerk_user_id ON public.listing_claim_requests USING btree (clerk_user_id);

CREATE INDEX idx_lcr_listing_id ON public.listing_claim_requests USING btree (listing_id);

CREATE INDEX idx_lcr_pending ON public.listing_claim_requests USING btree (status) WHERE (status = 'pending'::text);

CREATE INDEX idx_lcr_status ON public.listing_claim_requests USING btree (status);

CREATE INDEX lcr_listing_idx ON public.listing_claim_requests USING btree (listing_id);

CREATE INDEX lcr_status_idx ON public.listing_claim_requests USING btree (status);

CREATE INDEX idx_orders_created_at ON public.orders USING btree (created_at DESC);

CREATE INDEX idx_orders_farm_id ON public.orders USING btree (farm_id);

CREATE INDEX idx_orders_farm_status ON public.orders USING btree (farm_id, status);

CREATE INDEX idx_orders_payment_status ON public.orders USING btree (payment_status);

CREATE INDEX idx_orders_status ON public.orders USING btree (status);

CREATE INDEX idx_orders_user_id ON public.orders USING btree (user_id);

CREATE INDEX idx_producer_requests_listing ON public.producer_requests USING btree (listing_id);

CREATE INDEX idx_producer_requests_status ON public.producer_requests USING btree (status);

CREATE INDEX idx_producer_requests_type ON public.producer_requests USING btree (type);

CREATE INDEX idx_producer_requests_user_id ON public.producer_requests USING btree (user_id);

CREATE INDEX idx_products_active ON public.products USING btree (active);

CREATE INDEX idx_products_active_stock ON public.products USING btree (active, stock_status) WHERE (active = true);

CREATE INDEX idx_products_available ON public.products USING btree (available);

CREATE INDEX idx_products_category ON public.products USING btree (category);

CREATE INDEX idx_products_farm_id ON public.products USING btree (farm_id) WHERE (active = true);

CREATE INDEX idx_products_listing_id ON public.products USING btree (listing_id);

CREATE INDEX idx_products_name ON public.products USING btree (name);

CREATE INDEX idx_profiles_farm_id ON public.profiles USING btree (farm_id) WHERE (farm_id IS NOT NULL);

CREATE INDEX idx_profiles_role ON public.profiles USING btree (role);

CREATE INDEX idx_profiles_user_id ON public.profiles USING btree (user_id);

CREATE INDEX idx_reviews_created_at ON public.reviews USING btree (created_at DESC);

CREATE INDEX idx_reviews_listing_approved ON public.reviews USING btree (listing_id, status) WHERE ((status)::text = 'approved'::text);

CREATE INDEX idx_reviews_listing_id ON public.reviews USING btree (listing_id);

CREATE INDEX idx_reviews_rating ON public.reviews USING btree (rating);

CREATE INDEX idx_reviews_status ON public.reviews USING btree (status);

CREATE INDEX idx_reviews_user_id ON public.reviews USING btree (user_id);

ALTER TABLE public."farmer_requests" ENABLE ROW LEVEL SECURITY;

ALTER TABLE public."listing" ENABLE ROW LEVEL SECURITY;

ALTER TABLE public."listingImages" ENABLE ROW LEVEL SECURITY;

ALTER TABLE public."listing_claim_requests" ENABLE ROW LEVEL SECURITY;

ALTER TABLE public."orders" ENABLE ROW LEVEL SECURITY;

ALTER TABLE public."producer_requests" ENABLE ROW LEVEL SECURITY;

ALTER TABLE public."products" ENABLE ROW LEVEL SECURITY;

ALTER TABLE public."profiles" ENABLE ROW LEVEL SECURITY;

ALTER TABLE public."review_reports" ENABLE ROW LEVEL SECURITY;

ALTER TABLE public."review_votes" ENABLE ROW LEVEL SECURITY;

ALTER TABLE public."reviews" ENABLE ROW LEVEL SECURITY;

CREATE POLICY "farmer_requests_admin_delete" ON "public"."farmer_requests" AS PERMISSIVE FOR DELETE TO "authenticated" USING (is_admin());

CREATE POLICY "farmer_requests_admin_read" ON "public"."farmer_requests" AS PERMISSIVE FOR SELECT TO "authenticated" USING (is_admin());

CREATE POLICY "farmer_requests_admin_update" ON "public"."farmer_requests" AS PERMISSIVE FOR UPDATE TO "authenticated" USING (is_admin()) WITH CHECK (is_admin());

CREATE POLICY "farmer_requests_insert" ON "public"."farmer_requests" AS PERMISSIVE FOR INSERT TO "authenticated" WITH CHECK ((user_id = (auth.jwt() ->> 'sub'::text)));

CREATE POLICY "farmer_requests_owner_read" ON "public"."farmer_requests" AS PERMISSIVE FOR SELECT TO "authenticated" USING ((user_id = (auth.jwt() ->> 'sub'::text)));

CREATE POLICY "Allow read unclaimed listings" ON "public"."listing" AS PERMISSIVE FOR SELECT TO PUBLIC USING ((clerk_user_id IS NULL));

CREATE POLICY "listing_admin_delete" ON "public"."listing" AS PERMISSIVE FOR DELETE TO "authenticated" USING (is_admin());

CREATE POLICY "listing_admin_read" ON "public"."listing" AS PERMISSIVE FOR SELECT TO "authenticated" USING (is_admin());

CREATE POLICY "listing_admin_update" ON "public"."listing" AS PERMISSIVE FOR UPDATE TO "authenticated" USING (is_admin()) WITH CHECK (is_admin());

CREATE POLICY "listing_farmer_insert" ON "public"."listing" AS PERMISSIVE FOR INSERT TO "authenticated" WITH CHECK ((is_farmer() AND (clerk_user_id = current_clerk_user_id())));

CREATE POLICY "listing_owner_delete" ON "public"."listing" AS PERMISSIVE FOR DELETE TO "authenticated" USING ((clerk_user_id = (auth.jwt() ->> 'sub'::text)));

CREATE POLICY "listing_owner_read" ON "public"."listing" AS PERMISSIVE FOR SELECT TO "authenticated" USING ((clerk_user_id = (auth.jwt() ->> 'sub'::text)));

CREATE POLICY "listing_owner_update" ON "public"."listing" AS PERMISSIVE FOR UPDATE TO "authenticated" USING ((clerk_user_id = (auth.jwt() ->> 'sub'::text))) WITH CHECK ((clerk_user_id = (auth.jwt() ->> 'sub'::text)));

CREATE POLICY "listing_public_read" ON "public"."listing" AS PERMISSIVE FOR SELECT TO "anon", "authenticated" USING ((active = true));

CREATE POLICY "listingImages_owner_delete" ON "public"."listingImages" AS PERMISSIVE FOR DELETE TO "authenticated" USING ((EXISTS ( SELECT 1
   FROM listing l
  WHERE ((l.id = "listingImages".listing_id) AND (l.clerk_user_id = (auth.jwt() ->> 'sub'::text))))));

CREATE POLICY "listingImages_owner_update" ON "public"."listingImages" AS PERMISSIVE FOR UPDATE TO "authenticated" USING ((EXISTS ( SELECT 1
   FROM listing l
  WHERE ((l.id = "listingImages".listing_id) AND (l.clerk_user_id = (auth.jwt() ->> 'sub'::text)))))) WITH CHECK ((EXISTS ( SELECT 1
   FROM listing l
  WHERE ((l.id = "listingImages".listing_id) AND (l.clerk_user_id = (auth.jwt() ->> 'sub'::text))))));

CREATE POLICY "listingImages_public_read" ON "public"."listingImages" AS PERMISSIVE FOR SELECT TO "anon", "authenticated" USING ((EXISTS ( SELECT 1
   FROM listing l
  WHERE ((l.id = "listingImages".listing_id) AND (l.active = true)))));

CREATE POLICY "listingimages_admin_delete" ON "public"."listingImages" AS PERMISSIVE FOR DELETE TO "authenticated" USING (is_admin());

CREATE POLICY "listingimages_admin_read" ON "public"."listingImages" AS PERMISSIVE FOR SELECT TO "authenticated" USING (is_admin());

CREATE POLICY "listingimages_admin_update" ON "public"."listingImages" AS PERMISSIVE FOR UPDATE TO "authenticated" USING (is_admin()) WITH CHECK (is_admin());

CREATE POLICY "listingimages_farmer_insert" ON "public"."listingImages" AS PERMISSIVE FOR INSERT TO "authenticated" WITH CHECK ((is_farmer() AND (EXISTS ( SELECT 1
   FROM listing l
  WHERE ((l.id = "listingImages".listing_id) AND (l.clerk_user_id = current_clerk_user_id()))))));

CREATE POLICY "lcr_insert_own" ON "public"."listing_claim_requests" AS PERMISSIVE FOR INSERT TO PUBLIC WITH CHECK (((auth.jwt() ->> 'sub'::text) = clerk_user_id));

CREATE POLICY "lcr_select_own" ON "public"."listing_claim_requests" AS PERMISSIVE FOR SELECT TO PUBLIC USING (((auth.jwt() ->> 'sub'::text) = clerk_user_id));

CREATE POLICY "orders_farmer_select" ON "public"."orders" AS PERMISSIVE FOR SELECT TO "authenticated" USING ((EXISTS ( SELECT 1
   FROM profiles p
  WHERE ((p.user_id = (auth.jwt() ->> 'sub'::text)) AND (p.role = ANY (ARRAY['farmer'::text, 'admin'::text])) AND (p.farm_id = orders.farm_id)))));

CREATE POLICY "orders_user_insert" ON "public"."orders" AS PERMISSIVE FOR INSERT TO "authenticated" WITH CHECK ((user_id = (auth.jwt() ->> 'sub'::text)));

CREATE POLICY "orders_user_select" ON "public"."orders" AS PERMISSIVE FOR SELECT TO "authenticated" USING ((user_id = (auth.jwt() ->> 'sub'::text)));

CREATE POLICY "orders_user_update" ON "public"."orders" AS PERMISSIVE FOR UPDATE TO "authenticated" USING ((user_id = (auth.jwt() ->> 'sub'::text))) WITH CHECK ((user_id = (auth.jwt() ->> 'sub'::text)));

CREATE POLICY "Users can insert their own requests" ON "public"."producer_requests" AS PERMISSIVE FOR INSERT TO PUBLIC WITH CHECK ((user_id = (auth.uid())::text));

CREATE POLICY "Users can view their own requests" ON "public"."producer_requests" AS PERMISSIVE FOR SELECT TO PUBLIC USING ((user_id = (auth.uid())::text));

CREATE POLICY "Enable read access for all products" ON "public"."products" AS PERMISSIVE FOR ALL TO PUBLIC USING (true);

CREATE POLICY "products_farmer_manage" ON "public"."products" AS PERMISSIVE FOR ALL TO PUBLIC USING ((EXISTS ( SELECT 1
   FROM profiles p
  WHERE ((p.user_id = (auth.jwt() ->> 'sub'::text)) AND (p.role = ANY (ARRAY['farmer'::text, 'admin'::text])) AND (p.farm_id = products.farm_id))))) WITH CHECK ((EXISTS ( SELECT 1
   FROM profiles p
  WHERE ((p.user_id = (auth.jwt() ->> 'sub'::text)) AND (p.role = ANY (ARRAY['farmer'::text, 'admin'::text])) AND (p.farm_id = products.farm_id)))));

CREATE POLICY "profiles_admin_read" ON "public"."profiles" AS PERMISSIVE FOR SELECT TO "authenticated" USING (is_admin());

CREATE POLICY "profiles_admin_update" ON "public"."profiles" AS PERMISSIVE FOR UPDATE TO "authenticated" USING (is_admin()) WITH CHECK (is_admin());

CREATE POLICY "profiles_self_insert" ON "public"."profiles" AS PERMISSIVE FOR INSERT TO PUBLIC WITH CHECK ((user_id = current_clerk_user_id()));

CREATE POLICY "profiles_self_read" ON "public"."profiles" AS PERMISSIVE FOR SELECT TO "authenticated" USING ((user_id = current_clerk_user_id()));

CREATE POLICY "profiles_self_update" ON "public"."profiles" AS PERMISSIVE FOR UPDATE TO "authenticated" USING ((user_id = current_clerk_user_id())) WITH CHECK ((user_id = current_clerk_user_id()));

CREATE POLICY "Public 16jtzx8_0" ON "storage"."objects" AS PERMISSIVE FOR SELECT TO PUBLIC USING ((bucket_id = 'listingImages'::text));

CREATE POLICY "Public 16jtzx8_1" ON "storage"."objects" AS PERMISSIVE FOR INSERT TO PUBLIC WITH CHECK ((bucket_id = 'listingImages'::text));

CREATE POLICY "Public 16jtzx8_2" ON "storage"."objects" AS PERMISSIVE FOR UPDATE TO PUBLIC USING ((bucket_id = 'listingImages'::text));

CREATE POLICY "Public 16jtzx8_3" ON "storage"."objects" AS PERMISSIVE FOR DELETE TO PUBLIC USING ((bucket_id = 'listingImages'::text));

CREATE TRIGGER trigger_handle_farmer_request_approval AFTER UPDATE ON farmer_requests FOR EACH ROW EXECUTE FUNCTION handle_farmer_request_approval();

CREATE TRIGGER update_farmer_requests_updated_at BEFORE UPDATE ON farmer_requests FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER trigger_lcr_updated_at BEFORE UPDATE ON listing_claim_requests FOR EACH ROW EXECUTE FUNCTION update_lcr_updated_at();

CREATE TRIGGER trg_orders_updated_at BEFORE UPDATE ON orders FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER on_producer_request_approval AFTER UPDATE ON producer_requests FOR EACH ROW EXECUTE FUNCTION handle_producer_request_approval();

CREATE TRIGGER producer_requests_updated_at BEFORE UPDATE ON producer_requests FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER trigger_handle_producer_request_approval AFTER UPDATE ON producer_requests FOR EACH ROW EXECUTE FUNCTION handle_producer_request_approval();

CREATE TRIGGER trg_prevent_profile_role_change BEFORE UPDATE ON profiles FOR EACH ROW EXECUTE FUNCTION prevent_profile_role_change();

CREATE TRIGGER trg_prevent_profiles_sensitive_changes BEFORE UPDATE ON profiles FOR EACH ROW EXECUTE FUNCTION prevent_profiles_sensitive_changes();

CREATE TRIGGER update_reviews_updated_at BEFORE UPDATE ON reviews FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

GRANT USAGE ON SCHEMA public TO anon, authenticated, service_role;

REVOKE ALL ON ALL TABLES IN SCHEMA public FROM PUBLIC, anon, authenticated, service_role;

REVOKE ALL ON ALL SEQUENCES IN SCHEMA public FROM PUBLIC, anon, authenticated, service_role;

-- Function ACLs below retain the source grants; extension-owned functions retain their defaults.
REVOKE ALL ON FUNCTION public."current_clerk_user_id"() FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON FUNCTION public."generate_claim_code"() FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON FUNCTION public."handle_farmer_request_approval"() FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON FUNCTION public."handle_producer_request_approval"() FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON FUNCTION public."is_admin"() FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON FUNCTION public."is_farmer"() FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON FUNCTION public."prevent_profile_role_change"() FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON FUNCTION public."prevent_profiles_sensitive_changes"() FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON FUNCTION public."set_updated_at"() FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON FUNCTION public."update_lcr_updated_at"() FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON FUNCTION public."update_updated_at_column"() FROM PUBLIC, anon, authenticated, service_role;

GRANT DELETE ON public."farmer_requests" TO "anon";

GRANT INSERT ON public."farmer_requests" TO "anon";

GRANT REFERENCES ON public."farmer_requests" TO "anon";

GRANT SELECT ON public."farmer_requests" TO "anon";

GRANT TRIGGER ON public."farmer_requests" TO "anon";

GRANT TRUNCATE ON public."farmer_requests" TO "anon";

GRANT UPDATE ON public."farmer_requests" TO "anon";

GRANT DELETE ON public."farmer_requests" TO "authenticated";

GRANT INSERT ON public."farmer_requests" TO "authenticated";

GRANT REFERENCES ON public."farmer_requests" TO "authenticated";

GRANT SELECT ON public."farmer_requests" TO "authenticated";

GRANT TRIGGER ON public."farmer_requests" TO "authenticated";

GRANT TRUNCATE ON public."farmer_requests" TO "authenticated";

GRANT UPDATE ON public."farmer_requests" TO "authenticated";

GRANT DELETE ON public."farmer_requests" TO "service_role";

GRANT INSERT ON public."farmer_requests" TO "service_role";

GRANT REFERENCES ON public."farmer_requests" TO "service_role";

GRANT SELECT ON public."farmer_requests" TO "service_role";

GRANT TRIGGER ON public."farmer_requests" TO "service_role";

GRANT TRUNCATE ON public."farmer_requests" TO "service_role";

GRANT UPDATE ON public."farmer_requests" TO "service_role";

GRANT DELETE ON public."listing" TO "anon";

GRANT INSERT ON public."listing" TO "anon";

GRANT REFERENCES ON public."listing" TO "anon";

GRANT SELECT ON public."listing" TO "anon";

GRANT TRIGGER ON public."listing" TO "anon";

GRANT TRUNCATE ON public."listing" TO "anon";

GRANT UPDATE ON public."listing" TO "anon";

GRANT DELETE ON public."listing" TO "authenticated";

GRANT INSERT ON public."listing" TO "authenticated";

GRANT REFERENCES ON public."listing" TO "authenticated";

GRANT SELECT ON public."listing" TO "authenticated";

GRANT TRIGGER ON public."listing" TO "authenticated";

GRANT TRUNCATE ON public."listing" TO "authenticated";

GRANT UPDATE ON public."listing" TO "authenticated";

GRANT DELETE ON public."listing" TO "service_role";

GRANT INSERT ON public."listing" TO "service_role";

GRANT REFERENCES ON public."listing" TO "service_role";

GRANT SELECT ON public."listing" TO "service_role";

GRANT TRIGGER ON public."listing" TO "service_role";

GRANT TRUNCATE ON public."listing" TO "service_role";

GRANT UPDATE ON public."listing" TO "service_role";

GRANT DELETE ON public."listingImages" TO "anon";

GRANT INSERT ON public."listingImages" TO "anon";

GRANT REFERENCES ON public."listingImages" TO "anon";

GRANT SELECT ON public."listingImages" TO "anon";

GRANT TRIGGER ON public."listingImages" TO "anon";

GRANT TRUNCATE ON public."listingImages" TO "anon";

GRANT UPDATE ON public."listingImages" TO "anon";

GRANT DELETE ON public."listingImages" TO "authenticated";

GRANT INSERT ON public."listingImages" TO "authenticated";

GRANT REFERENCES ON public."listingImages" TO "authenticated";

GRANT SELECT ON public."listingImages" TO "authenticated";

GRANT TRIGGER ON public."listingImages" TO "authenticated";

GRANT TRUNCATE ON public."listingImages" TO "authenticated";

GRANT UPDATE ON public."listingImages" TO "authenticated";

GRANT DELETE ON public."listingImages" TO "service_role";

GRANT INSERT ON public."listingImages" TO "service_role";

GRANT REFERENCES ON public."listingImages" TO "service_role";

GRANT SELECT ON public."listingImages" TO "service_role";

GRANT TRIGGER ON public."listingImages" TO "service_role";

GRANT TRUNCATE ON public."listingImages" TO "service_role";

GRANT UPDATE ON public."listingImages" TO "service_role";

GRANT DELETE ON public."listing_claim_requests" TO "anon";

GRANT INSERT ON public."listing_claim_requests" TO "anon";

GRANT REFERENCES ON public."listing_claim_requests" TO "anon";

GRANT SELECT ON public."listing_claim_requests" TO "anon";

GRANT TRIGGER ON public."listing_claim_requests" TO "anon";

GRANT TRUNCATE ON public."listing_claim_requests" TO "anon";

GRANT UPDATE ON public."listing_claim_requests" TO "anon";

GRANT DELETE ON public."listing_claim_requests" TO "authenticated";

GRANT INSERT ON public."listing_claim_requests" TO "authenticated";

GRANT REFERENCES ON public."listing_claim_requests" TO "authenticated";

GRANT SELECT ON public."listing_claim_requests" TO "authenticated";

GRANT TRIGGER ON public."listing_claim_requests" TO "authenticated";

GRANT TRUNCATE ON public."listing_claim_requests" TO "authenticated";

GRANT UPDATE ON public."listing_claim_requests" TO "authenticated";

GRANT DELETE ON public."listing_claim_requests" TO "service_role";

GRANT INSERT ON public."listing_claim_requests" TO "service_role";

GRANT REFERENCES ON public."listing_claim_requests" TO "service_role";

GRANT SELECT ON public."listing_claim_requests" TO "service_role";

GRANT TRIGGER ON public."listing_claim_requests" TO "service_role";

GRANT TRUNCATE ON public."listing_claim_requests" TO "service_role";

GRANT UPDATE ON public."listing_claim_requests" TO "service_role";

GRANT DELETE ON public."orders" TO "anon";

GRANT INSERT ON public."orders" TO "anon";

GRANT REFERENCES ON public."orders" TO "anon";

GRANT SELECT ON public."orders" TO "anon";

GRANT TRIGGER ON public."orders" TO "anon";

GRANT TRUNCATE ON public."orders" TO "anon";

GRANT UPDATE ON public."orders" TO "anon";

GRANT DELETE ON public."orders" TO "authenticated";

GRANT INSERT ON public."orders" TO "authenticated";

GRANT REFERENCES ON public."orders" TO "authenticated";

GRANT SELECT ON public."orders" TO "authenticated";

GRANT TRIGGER ON public."orders" TO "authenticated";

GRANT TRUNCATE ON public."orders" TO "authenticated";

GRANT UPDATE ON public."orders" TO "authenticated";

GRANT DELETE ON public."orders" TO "service_role";

GRANT INSERT ON public."orders" TO "service_role";

GRANT REFERENCES ON public."orders" TO "service_role";

GRANT SELECT ON public."orders" TO "service_role";

GRANT TRIGGER ON public."orders" TO "service_role";

GRANT TRUNCATE ON public."orders" TO "service_role";

GRANT UPDATE ON public."orders" TO "service_role";

GRANT DELETE ON public."osm_import_review" TO "anon";

GRANT INSERT ON public."osm_import_review" TO "anon";

GRANT REFERENCES ON public."osm_import_review" TO "anon";

GRANT SELECT ON public."osm_import_review" TO "anon";

GRANT TRIGGER ON public."osm_import_review" TO "anon";

GRANT TRUNCATE ON public."osm_import_review" TO "anon";

GRANT UPDATE ON public."osm_import_review" TO "anon";

GRANT DELETE ON public."osm_import_review" TO "authenticated";

GRANT INSERT ON public."osm_import_review" TO "authenticated";

GRANT REFERENCES ON public."osm_import_review" TO "authenticated";

GRANT SELECT ON public."osm_import_review" TO "authenticated";

GRANT TRIGGER ON public."osm_import_review" TO "authenticated";

GRANT TRUNCATE ON public."osm_import_review" TO "authenticated";

GRANT UPDATE ON public."osm_import_review" TO "authenticated";

GRANT DELETE ON public."osm_import_review" TO "service_role";

GRANT INSERT ON public."osm_import_review" TO "service_role";

GRANT REFERENCES ON public."osm_import_review" TO "service_role";

GRANT SELECT ON public."osm_import_review" TO "service_role";

GRANT TRIGGER ON public."osm_import_review" TO "service_role";

GRANT TRUNCATE ON public."osm_import_review" TO "service_role";

GRANT UPDATE ON public."osm_import_review" TO "service_role";

GRANT DELETE ON public."producer_requests" TO "anon";

GRANT INSERT ON public."producer_requests" TO "anon";

GRANT REFERENCES ON public."producer_requests" TO "anon";

GRANT SELECT ON public."producer_requests" TO "anon";

GRANT TRIGGER ON public."producer_requests" TO "anon";

GRANT TRUNCATE ON public."producer_requests" TO "anon";

GRANT UPDATE ON public."producer_requests" TO "anon";

GRANT DELETE ON public."producer_requests" TO "authenticated";

GRANT INSERT ON public."producer_requests" TO "authenticated";

GRANT REFERENCES ON public."producer_requests" TO "authenticated";

GRANT SELECT ON public."producer_requests" TO "authenticated";

GRANT TRIGGER ON public."producer_requests" TO "authenticated";

GRANT TRUNCATE ON public."producer_requests" TO "authenticated";

GRANT UPDATE ON public."producer_requests" TO "authenticated";

GRANT DELETE ON public."producer_requests" TO "service_role";

GRANT INSERT ON public."producer_requests" TO "service_role";

GRANT REFERENCES ON public."producer_requests" TO "service_role";

GRANT SELECT ON public."producer_requests" TO "service_role";

GRANT TRIGGER ON public."producer_requests" TO "service_role";

GRANT TRUNCATE ON public."producer_requests" TO "service_role";

GRANT UPDATE ON public."producer_requests" TO "service_role";

GRANT DELETE ON public."products" TO "anon";

GRANT INSERT ON public."products" TO "anon";

GRANT REFERENCES ON public."products" TO "anon";

GRANT SELECT ON public."products" TO "anon";

GRANT TRIGGER ON public."products" TO "anon";

GRANT TRUNCATE ON public."products" TO "anon";

GRANT UPDATE ON public."products" TO "anon";

GRANT DELETE ON public."products" TO "authenticated";

GRANT INSERT ON public."products" TO "authenticated";

GRANT REFERENCES ON public."products" TO "authenticated";

GRANT SELECT ON public."products" TO "authenticated";

GRANT TRIGGER ON public."products" TO "authenticated";

GRANT TRUNCATE ON public."products" TO "authenticated";

GRANT UPDATE ON public."products" TO "authenticated";

GRANT DELETE ON public."products" TO "service_role";

GRANT INSERT ON public."products" TO "service_role";

GRANT REFERENCES ON public."products" TO "service_role";

GRANT SELECT ON public."products" TO "service_role";

GRANT TRIGGER ON public."products" TO "service_role";

GRANT TRUNCATE ON public."products" TO "service_role";

GRANT UPDATE ON public."products" TO "service_role";

GRANT DELETE ON public."profiles" TO "anon";

GRANT INSERT ON public."profiles" TO "anon";

GRANT REFERENCES ON public."profiles" TO "anon";

GRANT SELECT ON public."profiles" TO "anon";

GRANT TRIGGER ON public."profiles" TO "anon";

GRANT TRUNCATE ON public."profiles" TO "anon";

GRANT UPDATE ON public."profiles" TO "anon";

GRANT DELETE ON public."profiles" TO "authenticated";

GRANT INSERT ON public."profiles" TO "authenticated";

GRANT REFERENCES ON public."profiles" TO "authenticated";

GRANT SELECT ON public."profiles" TO "authenticated";

GRANT TRIGGER ON public."profiles" TO "authenticated";

GRANT TRUNCATE ON public."profiles" TO "authenticated";

GRANT UPDATE ON public."profiles" TO "authenticated";

GRANT DELETE ON public."profiles" TO "service_role";

GRANT INSERT ON public."profiles" TO "service_role";

GRANT REFERENCES ON public."profiles" TO "service_role";

GRANT SELECT ON public."profiles" TO "service_role";

GRANT TRIGGER ON public."profiles" TO "service_role";

GRANT TRUNCATE ON public."profiles" TO "service_role";

GRANT UPDATE ON public."profiles" TO "service_role";

GRANT DELETE ON public."review_reports" TO "anon";

GRANT INSERT ON public."review_reports" TO "anon";

GRANT REFERENCES ON public."review_reports" TO "anon";

GRANT SELECT ON public."review_reports" TO "anon";

GRANT TRIGGER ON public."review_reports" TO "anon";

GRANT TRUNCATE ON public."review_reports" TO "anon";

GRANT UPDATE ON public."review_reports" TO "anon";

GRANT DELETE ON public."review_reports" TO "authenticated";

GRANT INSERT ON public."review_reports" TO "authenticated";

GRANT REFERENCES ON public."review_reports" TO "authenticated";

GRANT SELECT ON public."review_reports" TO "authenticated";

GRANT TRIGGER ON public."review_reports" TO "authenticated";

GRANT TRUNCATE ON public."review_reports" TO "authenticated";

GRANT UPDATE ON public."review_reports" TO "authenticated";

GRANT DELETE ON public."review_reports" TO "service_role";

GRANT INSERT ON public."review_reports" TO "service_role";

GRANT REFERENCES ON public."review_reports" TO "service_role";

GRANT SELECT ON public."review_reports" TO "service_role";

GRANT TRIGGER ON public."review_reports" TO "service_role";

GRANT TRUNCATE ON public."review_reports" TO "service_role";

GRANT UPDATE ON public."review_reports" TO "service_role";

GRANT DELETE ON public."review_votes" TO "anon";

GRANT INSERT ON public."review_votes" TO "anon";

GRANT REFERENCES ON public."review_votes" TO "anon";

GRANT SELECT ON public."review_votes" TO "anon";

GRANT TRIGGER ON public."review_votes" TO "anon";

GRANT TRUNCATE ON public."review_votes" TO "anon";

GRANT UPDATE ON public."review_votes" TO "anon";

GRANT DELETE ON public."review_votes" TO "authenticated";

GRANT INSERT ON public."review_votes" TO "authenticated";

GRANT REFERENCES ON public."review_votes" TO "authenticated";

GRANT SELECT ON public."review_votes" TO "authenticated";

GRANT TRIGGER ON public."review_votes" TO "authenticated";

GRANT TRUNCATE ON public."review_votes" TO "authenticated";

GRANT UPDATE ON public."review_votes" TO "authenticated";

GRANT DELETE ON public."review_votes" TO "service_role";

GRANT INSERT ON public."review_votes" TO "service_role";

GRANT REFERENCES ON public."review_votes" TO "service_role";

GRANT SELECT ON public."review_votes" TO "service_role";

GRANT TRIGGER ON public."review_votes" TO "service_role";

GRANT TRUNCATE ON public."review_votes" TO "service_role";

GRANT UPDATE ON public."review_votes" TO "service_role";

GRANT DELETE ON public."reviews" TO "anon";

GRANT INSERT ON public."reviews" TO "anon";

GRANT REFERENCES ON public."reviews" TO "anon";

GRANT SELECT ON public."reviews" TO "anon";

GRANT TRIGGER ON public."reviews" TO "anon";

GRANT TRUNCATE ON public."reviews" TO "anon";

GRANT UPDATE ON public."reviews" TO "anon";

GRANT DELETE ON public."reviews" TO "authenticated";

GRANT INSERT ON public."reviews" TO "authenticated";

GRANT REFERENCES ON public."reviews" TO "authenticated";

GRANT SELECT ON public."reviews" TO "authenticated";

GRANT TRIGGER ON public."reviews" TO "authenticated";

GRANT TRUNCATE ON public."reviews" TO "authenticated";

GRANT UPDATE ON public."reviews" TO "authenticated";

GRANT DELETE ON public."reviews" TO "service_role";

GRANT INSERT ON public."reviews" TO "service_role";

GRANT REFERENCES ON public."reviews" TO "service_role";

GRANT SELECT ON public."reviews" TO "service_role";

GRANT TRIGGER ON public."reviews" TO "service_role";

GRANT TRUNCATE ON public."reviews" TO "service_role";

GRANT UPDATE ON public."reviews" TO "service_role";

GRANT SELECT ON SEQUENCE public."osm_import_review_id_seq" TO anon;

GRANT UPDATE ON SEQUENCE public."osm_import_review_id_seq" TO anon;

GRANT USAGE ON SEQUENCE public."osm_import_review_id_seq" TO anon;

GRANT SELECT ON SEQUENCE public."osm_import_review_id_seq" TO authenticated;

GRANT UPDATE ON SEQUENCE public."osm_import_review_id_seq" TO authenticated;

GRANT USAGE ON SEQUENCE public."osm_import_review_id_seq" TO authenticated;

GRANT SELECT ON SEQUENCE public."osm_import_review_id_seq" TO service_role;

GRANT UPDATE ON SEQUENCE public."osm_import_review_id_seq" TO service_role;

GRANT USAGE ON SEQUENCE public."osm_import_review_id_seq" TO service_role;

GRANT SELECT ON SEQUENCE public."listing_id_seq" TO anon;

GRANT UPDATE ON SEQUENCE public."listing_id_seq" TO anon;

GRANT USAGE ON SEQUENCE public."listing_id_seq" TO anon;

GRANT SELECT ON SEQUENCE public."listing_id_seq" TO authenticated;

GRANT UPDATE ON SEQUENCE public."listing_id_seq" TO authenticated;

GRANT USAGE ON SEQUENCE public."listing_id_seq" TO authenticated;

GRANT SELECT ON SEQUENCE public."listing_id_seq" TO service_role;

GRANT UPDATE ON SEQUENCE public."listing_id_seq" TO service_role;

GRANT USAGE ON SEQUENCE public."listing_id_seq" TO service_role;

GRANT SELECT ON SEQUENCE public."orders_id_seq" TO anon;

GRANT UPDATE ON SEQUENCE public."orders_id_seq" TO anon;

GRANT USAGE ON SEQUENCE public."orders_id_seq" TO anon;

GRANT SELECT ON SEQUENCE public."orders_id_seq" TO authenticated;

GRANT UPDATE ON SEQUENCE public."orders_id_seq" TO authenticated;

GRANT USAGE ON SEQUENCE public."orders_id_seq" TO authenticated;

GRANT SELECT ON SEQUENCE public."orders_id_seq" TO service_role;

GRANT UPDATE ON SEQUENCE public."orders_id_seq" TO service_role;

GRANT USAGE ON SEQUENCE public."orders_id_seq" TO service_role;

GRANT SELECT ON SEQUENCE public."listingImages_id_seq" TO anon;

GRANT UPDATE ON SEQUENCE public."listingImages_id_seq" TO anon;

GRANT USAGE ON SEQUENCE public."listingImages_id_seq" TO anon;

GRANT SELECT ON SEQUENCE public."listingImages_id_seq" TO authenticated;

GRANT UPDATE ON SEQUENCE public."listingImages_id_seq" TO authenticated;

GRANT USAGE ON SEQUENCE public."listingImages_id_seq" TO authenticated;

GRANT SELECT ON SEQUENCE public."listingImages_id_seq" TO service_role;

GRANT UPDATE ON SEQUENCE public."listingImages_id_seq" TO service_role;

GRANT USAGE ON SEQUENCE public."listingImages_id_seq" TO service_role;

GRANT SELECT ON SEQUENCE public."profiles_id_seq" TO anon;

GRANT UPDATE ON SEQUENCE public."profiles_id_seq" TO anon;

GRANT USAGE ON SEQUENCE public."profiles_id_seq" TO anon;

GRANT SELECT ON SEQUENCE public."profiles_id_seq" TO authenticated;

GRANT UPDATE ON SEQUENCE public."profiles_id_seq" TO authenticated;

GRANT USAGE ON SEQUENCE public."profiles_id_seq" TO authenticated;

GRANT SELECT ON SEQUENCE public."profiles_id_seq" TO service_role;

GRANT UPDATE ON SEQUENCE public."profiles_id_seq" TO service_role;

GRANT USAGE ON SEQUENCE public."profiles_id_seq" TO service_role;

GRANT SELECT ON SEQUENCE public."review_reports_id_seq" TO anon;

GRANT UPDATE ON SEQUENCE public."review_reports_id_seq" TO anon;

GRANT USAGE ON SEQUENCE public."review_reports_id_seq" TO anon;

GRANT SELECT ON SEQUENCE public."review_reports_id_seq" TO authenticated;

GRANT UPDATE ON SEQUENCE public."review_reports_id_seq" TO authenticated;

GRANT USAGE ON SEQUENCE public."review_reports_id_seq" TO authenticated;

GRANT SELECT ON SEQUENCE public."review_reports_id_seq" TO service_role;

GRANT UPDATE ON SEQUENCE public."review_reports_id_seq" TO service_role;

GRANT USAGE ON SEQUENCE public."review_reports_id_seq" TO service_role;

GRANT SELECT ON SEQUENCE public."review_votes_id_seq" TO anon;

GRANT UPDATE ON SEQUENCE public."review_votes_id_seq" TO anon;

GRANT USAGE ON SEQUENCE public."review_votes_id_seq" TO anon;

GRANT SELECT ON SEQUENCE public."review_votes_id_seq" TO authenticated;

GRANT UPDATE ON SEQUENCE public."review_votes_id_seq" TO authenticated;

GRANT USAGE ON SEQUENCE public."review_votes_id_seq" TO authenticated;

GRANT SELECT ON SEQUENCE public."review_votes_id_seq" TO service_role;

GRANT UPDATE ON SEQUENCE public."review_votes_id_seq" TO service_role;

GRANT USAGE ON SEQUENCE public."review_votes_id_seq" TO service_role;

GRANT SELECT ON SEQUENCE public."reviews_id_seq" TO anon;

GRANT UPDATE ON SEQUENCE public."reviews_id_seq" TO anon;

GRANT USAGE ON SEQUENCE public."reviews_id_seq" TO anon;

GRANT SELECT ON SEQUENCE public."reviews_id_seq" TO authenticated;

GRANT UPDATE ON SEQUENCE public."reviews_id_seq" TO authenticated;

GRANT USAGE ON SEQUENCE public."reviews_id_seq" TO authenticated;

GRANT SELECT ON SEQUENCE public."reviews_id_seq" TO service_role;

GRANT UPDATE ON SEQUENCE public."reviews_id_seq" TO service_role;

GRANT USAGE ON SEQUENCE public."reviews_id_seq" TO service_role;

GRANT SELECT ON SEQUENCE public."farmer_requests_id_seq" TO anon;

GRANT UPDATE ON SEQUENCE public."farmer_requests_id_seq" TO anon;

GRANT USAGE ON SEQUENCE public."farmer_requests_id_seq" TO anon;

GRANT SELECT ON SEQUENCE public."farmer_requests_id_seq" TO authenticated;

GRANT UPDATE ON SEQUENCE public."farmer_requests_id_seq" TO authenticated;

GRANT USAGE ON SEQUENCE public."farmer_requests_id_seq" TO authenticated;

GRANT SELECT ON SEQUENCE public."farmer_requests_id_seq" TO service_role;

GRANT UPDATE ON SEQUENCE public."farmer_requests_id_seq" TO service_role;

GRANT USAGE ON SEQUENCE public."farmer_requests_id_seq" TO service_role;

GRANT SELECT ON SEQUENCE public."products_id_seq" TO anon;

GRANT UPDATE ON SEQUENCE public."products_id_seq" TO anon;

GRANT USAGE ON SEQUENCE public."products_id_seq" TO anon;

GRANT SELECT ON SEQUENCE public."products_id_seq" TO authenticated;

GRANT UPDATE ON SEQUENCE public."products_id_seq" TO authenticated;

GRANT USAGE ON SEQUENCE public."products_id_seq" TO authenticated;

GRANT SELECT ON SEQUENCE public."products_id_seq" TO service_role;

GRANT UPDATE ON SEQUENCE public."products_id_seq" TO service_role;

GRANT USAGE ON SEQUENCE public."products_id_seq" TO service_role;

GRANT EXECUTE ON FUNCTION public."current_clerk_user_id"() TO PUBLIC;

GRANT EXECUTE ON FUNCTION public."current_clerk_user_id"() TO anon;

GRANT EXECUTE ON FUNCTION public."current_clerk_user_id"() TO authenticated;

GRANT EXECUTE ON FUNCTION public."current_clerk_user_id"() TO service_role;

GRANT EXECUTE ON FUNCTION public."generate_claim_code"() TO PUBLIC;

GRANT EXECUTE ON FUNCTION public."generate_claim_code"() TO anon;

GRANT EXECUTE ON FUNCTION public."generate_claim_code"() TO authenticated;

GRANT EXECUTE ON FUNCTION public."generate_claim_code"() TO service_role;

GRANT EXECUTE ON FUNCTION public."handle_farmer_request_approval"() TO PUBLIC;

GRANT EXECUTE ON FUNCTION public."handle_farmer_request_approval"() TO anon;

GRANT EXECUTE ON FUNCTION public."handle_farmer_request_approval"() TO authenticated;

GRANT EXECUTE ON FUNCTION public."handle_farmer_request_approval"() TO service_role;

GRANT EXECUTE ON FUNCTION public."handle_producer_request_approval"() TO PUBLIC;

GRANT EXECUTE ON FUNCTION public."handle_producer_request_approval"() TO anon;

GRANT EXECUTE ON FUNCTION public."handle_producer_request_approval"() TO authenticated;

GRANT EXECUTE ON FUNCTION public."handle_producer_request_approval"() TO service_role;

GRANT EXECUTE ON FUNCTION public."is_admin"() TO anon;

GRANT EXECUTE ON FUNCTION public."is_admin"() TO authenticated;

GRANT EXECUTE ON FUNCTION public."is_admin"() TO service_role;

GRANT EXECUTE ON FUNCTION public."is_farmer"() TO anon;

GRANT EXECUTE ON FUNCTION public."is_farmer"() TO authenticated;

GRANT EXECUTE ON FUNCTION public."is_farmer"() TO service_role;

GRANT EXECUTE ON FUNCTION public."prevent_profile_role_change"() TO PUBLIC;

GRANT EXECUTE ON FUNCTION public."prevent_profile_role_change"() TO anon;

GRANT EXECUTE ON FUNCTION public."prevent_profile_role_change"() TO authenticated;

GRANT EXECUTE ON FUNCTION public."prevent_profile_role_change"() TO service_role;

GRANT EXECUTE ON FUNCTION public."prevent_profiles_sensitive_changes"() TO PUBLIC;

GRANT EXECUTE ON FUNCTION public."prevent_profiles_sensitive_changes"() TO anon;

GRANT EXECUTE ON FUNCTION public."prevent_profiles_sensitive_changes"() TO authenticated;

GRANT EXECUTE ON FUNCTION public."prevent_profiles_sensitive_changes"() TO service_role;

GRANT EXECUTE ON FUNCTION public."set_updated_at"() TO PUBLIC;

GRANT EXECUTE ON FUNCTION public."set_updated_at"() TO anon;

GRANT EXECUTE ON FUNCTION public."set_updated_at"() TO authenticated;

GRANT EXECUTE ON FUNCTION public."set_updated_at"() TO service_role;

GRANT EXECUTE ON FUNCTION public."update_lcr_updated_at"() TO PUBLIC;

GRANT EXECUTE ON FUNCTION public."update_lcr_updated_at"() TO anon;

GRANT EXECUTE ON FUNCTION public."update_lcr_updated_at"() TO authenticated;

GRANT EXECUTE ON FUNCTION public."update_lcr_updated_at"() TO service_role;

GRANT EXECUTE ON FUNCTION public."update_updated_at_column"() TO PUBLIC;

GRANT EXECUTE ON FUNCTION public."update_updated_at_column"() TO anon;

GRANT EXECUTE ON FUNCTION public."update_updated_at_column"() TO authenticated;

GRANT EXECUTE ON FUNCTION public."update_updated_at_column"() TO service_role;

INSERT INTO storage.buckets (id, name, public, file_size_limit, allowed_mime_types) VALUES ('listingImages','listingImages',true,NULL,NULL);

commit;
